### prometheus.yml ###
global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files:
  - '/etc/prometheus/alert.rules'

# A scrape configuration for cadvisor:
scrape_configs:
  - job_name: 'cadvisor'
    scrape_interval: 5s
    scrape_timeout: 10s
    target_groups:
      - targets: ['192.168.33.10:8080']
